### PR TITLE
Fix output size limit handling

### LINKED ISSUE #119: `decompress_to_vec_zlib_with_limit` returns an error even when given the correct output size (bug?)
Hi! 

The function `decompress_to_vec_zlib_with_limit` __returns an error when the limit is set to the correct size of the decompressed data__. Is there something wrong with my code or is there a bug in the library? Here is a corresponding test I wrote that fails:

```rust

    #[test]
    fn inflate_with_exact_limit(){
        use miniz_oxide::inflate::{decompress_to_vec_zlib, decompress_to_vec_zlib_with_limit};

        let compressed_data = [
            120, 156, 237, 217, 65, 17, 194, 0, 16, 192, 192, 122, 193, 94, 13, 240, 232, 128, 12, 28, 160, 2, 53, 53, 130, 139, 220, 227, 118, 21, 228, 159, 227, 13, 0, 212, 126, 211, 1, 0, 176, 208, 99, 58, 0, 0, 22, 122, 78, 7, 0, 192, 66, 223, 233, 0, 0, 88, 200, 255, 5, 128, 158, 255, 11, 0, 61, 255, 23, 0, 122, 254, 47, 0, 244, 252, 95, 0, 232, 249, 191, 0, 208, 243, 127, 1, 160, 231, 255, 2, 64, 207, 255, 5, 128, 158, 255, 11, 0, 61, 255, 23, 0, 122, 254, 47, 0, 244, 252, 95, 0, 232, 249, 191, 0, 208, 243, 127, 1, 160, 231, 255, 2, 64, 207, 255, 5, 128, 158, 255, 11, 0, 61, 255, 23, 0, 122, 254, 47, 0, 244, 252, 95, 0, 232, 249, 191, 0, 208,
            243, 127, 1, 160, 231, 255, 2, 64, 207, 255, 5, 128, 158, 255, 11, 0, 61, 255, 23, 0, 122, 254, 47, 0, 244, 252, 95, 0, 232, 249, 191, 0, 208, 243, 127, 1, 160, 231, 255, 2, 64, 207, 255, 5, 128, 158, 255, 11, 0, 61, 255, 23, 0, 122, 254, 47, 0, 244, 252, 95, 0, 232, 249, 191, 0, 208, 243, 127, 1, 160, 231, 255, 2, 64, 207, 255, 5, 128, 158, 255, 11, 0, 61, 255, 23, 0, 122, 254, 47, 0, 244, 252, 95, 0, 232, 249, 191, 0, 208, 243, 127, 1, 160, 231, 255, 2, 64, 207, 255, 5, 128, 158, 255, 11, 0, 61, 255, 23, 0, 122, 254, 47, 0, 244, 252, 95, 0, 232, 249, 191, 0, 208, 243, 127,
            1, 160, 231, 255, 2, 64, 207, 255, 5, 128, 158, 255, 11, 0, 61, 255, 23, 0, 122, 247, 116, 0, 0, 44, 116, 78, 7, 0, 192, 66, 215, 116, 0, 0, 44, 244, 154, 14, 0, 128, 133, 62, 211, 1, 0, 176, 144, 255, 11, 0, 61, 255, 23, 0, 122, 254, 47, 0, 244, 252, 95, 0, 232, 249, 191, 0, 208, 243, 127, 1, 160, 231, 255, 2, 64, 207, 255, 5, 128, 158, 255, 11, 0, 61, 255, 23, 0, 122, 254, 47, 0, 244, 252, 95, 0, 232, 249, 191, 0, 208, 243, 127, 1, 160, 231, 255, 2, 64, 207, 255, 5, 128, 158, 255, 11, 0, 61, 255, 23, 0, 122, 254, 47, 0, 244, 252, 95, 0, 232, 249, 191, 0, 208, 243, 127, 1, 160, 231, 255, 2, 64, 207, 255, 5,
            128, 158, 255, 11, 0, 61, 255, 23, 0, 122, 254, 47, 0, 244, 252, 95, 0, 232, 249, 191, 0, 208, 243, 127, 1, 160, 231, 255, 2, 64, 207, 255, 5, 128, 158, 255, 11, 0, 61, 255, 23, 0, 122, 254, 47, 0, 244, 252, 95, 0, 232, 249, 191, 0, 208, 243, 127, 1, 160, 231, 255, 2, 64, 207, 255, 5, 128, 158, 255, 11, 0, 61, 255, 23, 0, 122, 254, 47, 0, 244, 252, 95, 0, 232, 249, 191, 0, 208, 243, 127, 1, 160, 231, 255, 2, 64, 207, 255, 5, 128, 158, 255, 11, 0, 61, 255, 23, 0, 122, 254, 47, 0, 244, 252, 95, 0, 232, 249, 191, 0, 208, 243, 127, 1, 160, 231, 255, 2, 64, 207, 255, 5, 128, 158, 255, 11, 0, 61, 255, 23, 0, 122, 254, 47, 0, 244, 254, 53, 209, 27, 197
        ].as_slice();

        let decompressed_size = decompress_to_vec_zlib(compressed_data)
            .expect("test is not valid, data must correctly decompress when not limited")
            .len();

        let _ = decompress_to_vec_zlib_with_limit(compressed_data, decompressed_size)
            .expect(format!("data decompression failed when limited to {}", decompressed_size).as_str());
    }


```

Using `miniz_oxide = "^0.5.3"`, no SIMD features.
Fails with the message `data decompression failed when limited to 245760: HasMoreOutput`.

The test also failed when given the limit `decompressed_size + 1` or `decompressed_size + 32`. It passed for limit `decompressed_size * 2`. 

Any ideas?

### PR DESCRIPTION
**Pull request by Shnatsel**
Fixes  #119

### CODE REVIEW

**Comment by oyvindln** [comment]
Thanks, nice work!

**Comment by Shnatsel** [comment]
Thanks for merging this quickly!

I'd appreciate a new release with this fix, as well. I have some code depending on the `*_with_limit` functions.

**Comment by oyvindln** [comment]
Yeah will try to get one out pretty quickly.

**Comment by johannesvollmer** [comment]
Cool :)

**Comment by Shnatsel** [comment]
Is there a chance to backport this to the 0.5.x series? The `*_with_limit` functions were introduced in 0.5.x, so it would be great if a semver-compatible version with the fix was available.

**Comment by oyvindln** [comment]
Yeah that shouldn't be too hard.

**Pull request merged**
